import { ChainId } from '@thienlk/sdk-code';

export const DEFAULT_BLOCKS_TO_LIVE: { [chain in ChainId]: number } = {
  [ChainId.MAINNET]: 5,
  [ChainId.GOERLI]: 5,
  [ChainId.SEPOLIA]: 5,
  [ChainId.OPTIMISM]: 5,
  [ChainId.OPTIMISM_GOERLI]: 5,
  [ChainId.OPTIMISM_SEPOLIA]: 5,
  [ChainId.ARBITRUM_ONE]: 5,
  [ChainId.ARBITRUM_GOERLI]: 5,
  [ChainId.ARBITRUM_SEPOLIA]: 5,
  [ChainId.POLYGON]: 5,
  [ChainId.POLYGON_MUMBAI]: 5,
  [ChainId.CELO]: 5,
  [ChainId.CELO_ALFAJORES]: 5,
  [ChainId.GNOSIS]: 5,
  [ChainId.MOONBEAM]: 5,
  [ChainId.BNB]: 5,
  [ChainId.AVALANCHE]: 5,
  [ChainId.BASE]: 5,
  [ChainId.BASE_GOERLI]: 5,
  [ChainId.BASE_SEPOLIA]: 5,
  [ChainId.ROOTSTOCK]: 5,
  [ChainId.BLAST]: 5,
  [ChainId.ZORA]: 5,
  [ChainId.ZORA_SEPOLIA]: 5,
  [ChainId.ZKSYNC]: 5,
  [ChainId.WORLDCHAIN]: 5,
  [ChainId.UNICHAIN_SEPOLIA]: 5,
  [ChainId.MONAD_TESTNET]: 5,
  [ChainId.UNICHAIN]: 5,
  [ChainId.SONEIUM]: 5,
  [ChainId.AURA_EUPHORIA]: 5,
};
