#!/bin/bash
set +e  # Continue on errors

if command -v git-secrets &> /dev/null
then # only run if git-secrets is installed
  # Initialise git-secrets configuration
  git-secrets --register-aws > /dev/null
  
  echo "Running git-secrets..."
  # Scans all files that are about to be committed.
  git-secrets --pre_commit_hook -- "$@"
  # Don't fail the commit if git-secrets fails
  echo "git-secrets scan complete"
else
  echo "git-secrets not found, skipping scan"
fi

if command -v trufflehog &> /dev/null
then # only run if trufflehog is installed
  echo "Running trufflehog..."
  trufflehog git file://. --since-commit HEAD --only-verified || true
  echo "trufflehog scan complete"
else
  echo "trufflehog not found, skipping scan"
fi

# Always exit successfully
exit 0
